alter table public.projects add column if not exists slug text unique;
alter table public.projects add column if not exists category text;
alter table public.projects add column if not exists tags jsonb default '[]'::jsonb;
alter table public.projects add column if not exists client text;
alter table public.projects add column if not exists project_role text;
alter table public.projects add column if not exists started_at date;
alter table public.projects add column if not exists completed_at date;
alter table public.projects add column if not exists challenge text;
alter table public.projects add column if not exists approach text;
alter table public.projects add column if not exists outcome text;
alter table public.projects add column if not exists credits text;
alter table public.projects add column if not exists gallery jsonb default '[]'::jsonb;
alter table public.projects add column if not exists is_featured boolean default false;
alter table public.projects add column if not exists is_published boolean default true;
alter table public.projects add column if not exists order_index integer default 0;

create table if not exists public.services (id bigint generated by default as identity primary key, slug text unique not null, title text not null, summary text, audience text, description text, deliverables jsonb default '[]'::jsonb, technologies jsonb default '[]'::jsonb, related_projects jsonb default '[]'::jsonb, is_published boolean default false, order_index integer default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.articles (id bigint generated by default as identity primary key, slug text unique not null, title text not null, excerpt text, category text, tags jsonb default '[]'::jsonb, cover_image text, author text, body jsonb default '[]'::jsonb, body_text text, reading_time integer default 1, published_at date, is_featured boolean default false, is_published boolean default false, order_index integer default 0, seo_title text, seo_description text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.testimonials (id bigint generated by default as identity primary key, name text not null, role text, organization text, quote text not null, photo_url text, permission_confirmed boolean default false, is_approved boolean default false, created_at timestamptz default now());
create table if not exists public.site_content (id bigint generated by default as identity primary key, key text unique not null, value text, updated_at timestamptz default now(), created_at timestamptz default now());

alter table public.services enable row level security;
alter table public.articles enable row level security;
alter table public.testimonials enable row level security;
alter table public.site_content enable row level security;
create policy "public read published services" on public.services for select using (is_published = true);
create policy "public read published articles" on public.articles for select using (is_published = true);
create policy "public read approved testimonials" on public.testimonials for select using (is_approved = true);
create policy "public submit testimonials" on public.testimonials for insert with check (is_approved = false);
create policy "public read site content" on public.site_content for select using (true);
create policy "admin manage services" on public.services for all to authenticated using (exists(select 1 from public.profiles where id = auth.uid() and role = 'admin')) with check (exists(select 1 from public.profiles where id = auth.uid() and role = 'admin'));
create policy "admin manage articles" on public.articles for all to authenticated using (exists(select 1 from public.profiles where id = auth.uid() and role = 'admin')) with check (exists(select 1 from public.profiles where id = auth.uid() and role = 'admin'));
create policy "admin manage testimonials" on public.testimonials for all to authenticated using (exists(select 1 from public.profiles where id = auth.uid() and role = 'admin')) with check (exists(select 1 from public.profiles where id = auth.uid() and role = 'admin'));
create policy "admin manage site content" on public.site_content for all to authenticated using (exists(select 1 from public.profiles where id = auth.uid() and role = 'admin')) with check (exists(select 1 from public.profiles where id = auth.uid() and role = 'admin'));
drop policy if exists "public read projects" on public.projects;
create policy "public read published projects" on public.projects for select using (is_published = true);

insert into public.services (slug,title,summary,audience,description,deliverables,technologies,is_published,order_index) values
('frontend-development','Front End Development','Responsive, accessible interfaces that turn product ideas into clear digital experiences.','Teams and organizations that need a modern public website or web application.','I build responsive React interfaces with careful attention to accessibility, performance, and maintainable component architecture.','["Responsive interface","Reusable component system","Accessibility review","Deployment support"]','["React","JavaScript","Tailwind CSS","Vite"]',true,1),
('backend-development','Back End Development','Reliable application data, authentication, storage, and APIs for useful web products.','Products that need secure data storage, user access, or content management.','I connect interfaces to practical back-end services, with protected data access and clear loading and error states.','["Database model","Authentication flow","API integration","Admin workflow"]','["Supabase","Node.js","REST APIs","PostgreSQL"]',true,2),
('devops-digital-services','DevOps and Digital Services','Deployment, domain, workflow, and operational support that keeps digital services dependable.','Small teams moving from a working build to a maintainable live service.','I help prepare applications for deployment, configure environments, document workflows, and improve operational reliability.','["Deployment setup","Environment configuration","Technical documentation","Maintenance plan"]','["Vercel","GitHub","Linux","CI workflows"]',true,3)
on conflict (slug) do nothing;

insert into public.articles (slug,title,excerpt,category,tags,cover_image,author,body,body_text,reading_time,published_at,is_published,order_index) values
('building-a-portfolio-as-a-working-system','Building a Portfolio as a Working System','A portfolio becomes more useful when projects, contact flows, and content management work together instead of behaving like a static gallery.','Engineering','["Portfolio","CMS","UX"]','/Coding.gif','Agegnehu Yelib Tesfa','[{"heading":"Start with the visitor journey","text":"A visitor should quickly understand who you are, what you can do, and where to find evidence."},{"heading":"Treat content as data","text":"Projects and articles should have stable URLs and structured fields."},{"heading":"Make every action honest","text":"A form should only confirm success after a real submission."}]','A portfolio should work as a connected system.',4,'2026-09-25',true,1),
('what-i-learned-connecting-react-and-supabase','What I Learned Connecting React and Supabase','Practical lessons from combining a React interface with authentication, storage, database policies, and an admin dashboard.','Learning','["React","Supabase","Security"]','/Animation1.gif','Agegnehu Yelib Tesfa','[{"heading":"Security starts with policies","text":"Hiding an admin link is not authorization. Database policies must protect every write."},{"heading":"Loading and error states matter","text":"Useful feedback prevents visitors and editors from guessing what happened."},{"heading":"Stable content models save time","text":"Slugs, publication status, timestamps, categories, and ordering make content easier to maintain."}]','Practical lessons from React and Supabase.',5,'2026-09-24',true,2)
on conflict (slug) do nothing;

insert into public.site_content (key,value) values
('about_bio','I am a software developer and digital systems specialist passionate about building practical, user-focused solutions. I enjoy working across front-end development, back-end development, and DevOps while continuously learning and exploring new technologies.'),
('about_quote','Using technology to create opportunities and positively impact others.'),
('about_mission','Build useful digital systems that make opportunities easier to access.'),
('about_values','Clarity, honesty, continuous learning, and dependable delivery.'),
('about_approach','Understand the problem, build in focused stages, test the real journey, and document the result.')
on conflict (key) do nothing;

update storage.buckets
set file_size_limit = 5242880,
    allowed_mime_types = array['image/jpeg','image/png','image/webp']
where id in ('project-images','certificate-images','profile-images');
