-- Run this file once in Supabase Dashboard > SQL Editor.
-- It is safe to run again if the table or policies already exist.

create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value text,
  updated_at timestamptz default now(),
  created_at timestamptz default now()
);

alter table public.site_content enable row level security;

drop policy if exists "public read site content" on public.site_content;
create policy "public read site content"
on public.site_content for select
to anon, authenticated
using (true);

drop policy if exists "admin manage site content" on public.site_content;
create policy "admin manage site content"
on public.site_content for all
to authenticated
using (
  exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  )
);

grant select on public.site_content to anon;
grant select, insert, update, delete on public.site_content to authenticated;
grant usage, select on sequence public.site_content_id_seq to authenticated;

insert into public.site_content (key, value)
values
  ('about_bio', 'I am a software developer and digital systems specialist passionate about building practical, user-focused solutions. I enjoy working across front-end development, back-end development, and DevOps while continuously learning and exploring new technologies.'),
  ('about_quote', 'Using technology to create opportunities and positively impact others.')
on conflict (key) do nothing;

notify pgrst, 'reload schema';
