-- Run this file in Supabase Dashboard > SQL Editor.
-- It creates every table used by Services, Articles, and Testimonials.
-- It is safe to run again.

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  summary text,
  audience text,
  description text,
  deliverables jsonb default '[]'::jsonb,
  technologies jsonb default '[]'::jsonb,
  related_projects jsonb default '[]'::jsonb,
  is_published boolean default false,
  order_index integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  excerpt text,
  category text,
  tags jsonb default '[]'::jsonb,
  cover_image text,
  author text,
  body jsonb default '[]'::jsonb,
  body_text text,
  reading_time integer default 1,
  published_at date,
  is_featured boolean default false,
  is_published boolean default false,
  order_index integer default 0,
  seo_title text,
  seo_description text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  organization text,
  quote text not null,
  photo_url text,
  permission_confirmed boolean default false,
  is_approved boolean default false,
  created_at timestamptz default now()
);

alter table public.services enable row level security;
alter table public.articles enable row level security;
alter table public.testimonials enable row level security;

drop policy if exists "public read published services" on public.services;
create policy "public read published services" on public.services
for select to anon, authenticated using (is_published = true);

drop policy if exists "public read published articles" on public.articles;
create policy "public read published articles" on public.articles
for select to anon, authenticated using (is_published = true);

drop policy if exists "public read approved testimonials" on public.testimonials;
create policy "public read approved testimonials" on public.testimonials
for select to anon, authenticated using (is_approved = true);

drop policy if exists "public submit testimonials" on public.testimonials;
create policy "public submit testimonials" on public.testimonials
for insert to anon, authenticated with check (is_approved = false and permission_confirmed = true);

drop policy if exists "admin manage services" on public.services;
create policy "admin manage services" on public.services for all to authenticated
using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'))
with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

drop policy if exists "admin manage articles" on public.articles;
create policy "admin manage articles" on public.articles for all to authenticated
using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'))
with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

drop policy if exists "admin manage testimonials" on public.testimonials;
create policy "admin manage testimonials" on public.testimonials for all to authenticated
using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'))
with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

grant select on public.services, public.articles to anon;
grant select, insert on public.testimonials to anon;
grant select, insert, update, delete on public.services, public.articles, public.testimonials to authenticated;
grant usage, select on sequence public.services_id_seq, public.articles_id_seq, public.testimonials_id_seq to anon, authenticated;

insert into public.services (slug, title, summary, audience, description, deliverables, technologies, is_published, order_index)
values
  ('frontend-development', 'Front End Development', 'Responsive, accessible interfaces that turn product ideas into clear digital experiences.', 'Teams and organizations that need a modern public website or web application.', 'I build responsive React interfaces with careful attention to accessibility, performance, and maintainable component architecture.', '["Responsive interface","Reusable component system","Accessibility review","Deployment support"]', '["React","JavaScript","Tailwind CSS","Vite"]', true, 1),
  ('backend-development', 'Back End Development', 'Reliable application data, authentication, storage, and APIs for useful web products.', 'Products that need secure data storage, user access, or content management.', 'I connect interfaces to practical back-end services, with protected data access and clear loading and error states.', '["Database model","Authentication flow","API integration","Admin workflow"]', '["Supabase","Node.js","REST APIs","PostgreSQL"]', true, 2),
  ('devops-digital-services', 'DevOps and Digital Services', 'Deployment, domain, workflow, and operational support that keeps digital services dependable.', 'Small teams moving from a working build to a maintainable live service.', 'I help prepare applications for deployment, configure environments, document workflows, and improve operational reliability.', '["Deployment setup","Environment configuration","Technical documentation","Maintenance plan"]', '["Vercel","GitHub","Linux","CI workflows"]', true, 3)
on conflict (slug) do nothing;

insert into public.articles (slug, title, excerpt, category, tags, cover_image, author, body, body_text, reading_time, published_at, is_published, order_index)
values
  ('building-a-portfolio-as-a-working-system', 'Your Website Is More Than a Pretty Poster', 'A good website should welcome people, answer their questions, and help them take the next step—even while you are sleeping.', 'Simple Ideas', '["Portfolio","Websites","Trust"]', '/insight-useful-website.webp', 'Agegnehu Yelib Tesfa', '[{"heading":"Imagine a helpful receptionist","text":"Your website is often the first person a visitor meets. It should quickly say who you are, what you do, and where to go next."},{"heading":"Pretty is good. Useful is better.","text":"Animations and colors can create a great first impression, but the website also needs to do a job."},{"heading":"The simple takeaway","text":"The best website helps visitors understand you, trust your work, and know what to do next."}]', 'A friendly story about why useful websites matter.', 3, '2026-09-25', true, 1),
  ('what-i-learned-connecting-react-and-supabase', 'What Building a Website Taught Me About Trust', 'A website is like a small shop: the door should open, private rooms need locks, and visitors should never be left wondering what happened.', 'Lessons Learned', '["Trust","Security","Learning"]', '/insight-digital-trust.webp', 'Agegnehu Yelib Tesfa', '[{"heading":"A hidden door still needs a lock","text":"Removing an admin button does not make private information safe. Real protection must work behind the scenes."},{"heading":"Never leave people staring at a silent screen","text":"A friendly status message is better than making visitors wonder whether they broke the website."},{"heading":"Good organization is a superpower","text":"Clear names and tidy information make a website easier to update and grow."}]', 'Simple lessons about trust and clear feedback.', 3, '2026-09-24', true, 2)
on conflict (slug) do nothing;

-- Existing seeded articles also receive the new optimized covers when this migration is rerun.
update public.articles set cover_image = '/insight-useful-website.webp'
where slug = 'building-a-portfolio-as-a-working-system';

update public.articles set cover_image = '/insight-digital-trust.webp'
where slug = 'what-i-learned-connecting-react-and-supabase';

notify pgrst, 'reload schema';
